# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20171105_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user',
            new_name='owner',
        ),
    ]
