# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
