# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20171105_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='owner',
            new_name='user',
        ),
    ]
