# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_auto_20171105_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=999)),
                ('repetitions', models.IntegerField(default=False)),
                ('category', models.CharField(default='Strength Training', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.Workout')),
            ],
        ),
    ]
